### ISSUE TITLE
Error: Ancestor Not Found

### ISSUE THREAD

**Issue by sshearing** [huggingface/chat-ui#870]
I posted this issue on spaces but thought it might be appropriate to share it here as well. Link to the original discussion:
https://huggingface.co/spaces/huggingchat/chat-ui/discussions/373#65d4d81e5531669ed283710b

Having some issues setting up huggingchat locally. I set up mongodb using the container provided in the setup and am able to run the chat UI. I do a local install of the chat UI. I replace the model endpoints with some text generation inference endpoints we have set up. I made no other changes to the config (other than the model endpoints and the mongo db path as directed). I can select models and send a message to the model and get a response. However, as soon as I try to send a second message, I get the following error:

Error: Ancestor not found
at /home/sshearing/chat-ui/src/lib/utils/tree/buildSubtree.ts:22:26
at Array.map ()
at Module.buildSubtree (/home/sshearing/chat-ui/src/lib/utils/tree/buildSubtree.ts:20:27)
at POST (/home/sshearing/chat-ui/src/routes/conversation/[id]/+server.ts:237:23)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.render_endpoint (/home/sshearing/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:43:18)
at async resolve (/home/sshearing/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:404:17)
at async Object.handle (/home/sshearing/chat-ui/src/hooks.server.ts:132:19)
at async Module.respond (/home/sshearing/chat-ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:20)
at async file:///home/sshearing/chat-ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22

User Oxaronick was able to provide some additional information as they are also running into this issue. Specifically, they say:
"I have started having the same issue today. First message in a chat is fine, second message results in the same stack trace. I'm running via docker compose. The compose file creates a mongodb container and an ollama container.

The issue is present in both of these images:
ghcr.io/huggingface/chat-ui         latest          ef44d918bdb8   5 hours ago     688MB
ghcr.io/huggingface/chat-ui         <none>          d0429d46f7f8   32 hours ago    688MB

From the browser dev tools, it looks like it's sending a POST to https://my.domain.com/conversation/<conversation_id> and getting a 500 back.

I bisected the published container images, and it looks like the last good image was sha256:def9c80dc77d0f37dd8bb2f1ba5728cb058366b14123043c1fb3178a4d766d14 (find it [here](https://github.com/huggingface/chat-ui/pkgs/container/chat-ui/versions?filters%5Bversion_type%5D=untagged&page=3)). As a workaround, one can pin this image with docker tag for now.

The next published image (sha256:486a0f652ab43a1dcd332dcca97b393fcfe767c67cb4581098c0600820b9c6d7) is an arm64 image so I can't test that on my server, and the very next one (sha256:235588f6b9793a20607e8fc479eab4abc81aad1a591d82fe53e8af93ec16d287) has the "Ancestor not found" error."

**Comment by pcnudde** [comment]
I had the same issue of the second chat message resulting in the ancestor not found.
Solved it by setting the ORIGIN environment variable.
docker run -p 3000:3000 -e ORIGIN='http://localhost:3000' containername

(but this is the first time I deal with this codebase or node, so I don't really know what I am doing :)

**Comment by pcnudde** [comment]
Setting the ORIGIN solved my issue for localhost, however once I set it up under HTTPS under a normal URL I always get the Ancestor not found issue, and I no idea how to fix it.

**Comment by sshearing** [comment]
Got some more information from the huggingchat spaces:

comment 1:
Got this, too. First failing commit is the current head [e6addfc54e52](https://huggingface.co/spaces/huggingchat/chat-ui/commit/e6addfc54e52) ("Conversation trees ([#223](https://huggingface.co/spaces/huggingchat/chat-ui/discussions/223)) (#807)")
Unfortunately, no history of the merged branch or useful commit messages.

another comment:
I had the same problem when building my docker image locally, for me it was caused by not having ORIGIN set when running PM2.
running locally like this made the problem go away:
docker run -p 3000:3000 -e ORIGIN='http://localhost:3000'/ containername

This problem was independent of docker for me. npm run preview worked, but just running node or pm2 did not.

comments 3 + 4:
I had the same problem when building my docker image locally, for me it was caused by not having ORIGIN set when running PM2.
running locally like this made the problem go away:
docker run -p 3000:3000 -e ORIGIN='http://localhost:3000'/ containername

This problem was independent of docker for me. npm run preview worked, but just running node or pm2 did not.

But there is something strange still going on. I get everything to run fine when using localhost, but as soon as I run the container on another server and use an actual IP address the POST to /conversation gives a 405.

**Comment by nsarrazin** [comment]
Looks related to [this](https://github.com/huggingface/chat-ui/issues/868) ? Will be taking a look to fix this

**Comment by sshearing** [comment]
Oh I was having that issue as well but found a fix. I ran into this when I was setting up my server on 0.0.0.0 instead of localhost and tried to use http instead of https. When I switched to https this got fixed. However, that doesn't mean the issues aren't related, just that I found a workaround for that one.

**Comment by nsarrazin** [comment]
Hi I merged some changes to main, can you pull the latest version and tell me if things are working better on your hand ? Feel free to reopen if not!

**Comment by sshearing** [comment]
I pulled and tested the new change, ancestor not found issue is still happening.

**Comment by nsarrazin** [comment]
Thanks for testing, taking a look now with a fully local setup :smile:

**Comment by nsarrazin** [comment]
Maybe obvious but could you make sure that `PUBLIC_ORIGIN` in your `.env.` is set to the public-facing URL you use to access your app ?

For example for HuggingChat it would be `PUBLIC_ORIGIN=https://huggingface.co` (see [here](https://github.com/huggingface/chat-ui/blob/main/.env.template#L260))

Let me know if that fixes it.

**Comment by sshearing** [comment]
yes my public origin is set to the correct address (cannot share here). This did not solve the issue.

**Comment by nsarrazin** [comment]
Can you try again with the latest changes? I  managed toreproduce the issue locally and my changes fixed it for me. Let me know if it works for you too :smile:

**Comment by sshearing** [comment]
success! I was able to query the model twice in one conversation! thank you!

**Comment by nsarrazin** [comment]
Thanks for the help with this issue! Closing the ticket now 😁
